<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="0"
            tests="0">

  <testsuite name="access-wallet"
    errors="0" failures="0" hostname="" id="" package="access-wallet" skipped="1"
    tests="0" time="0" timestamp="">
  

  
    <system-err>
        Error: An error occurred while retrieving a new session: &#34;Connection refused to 127.0.0.1:9515&#34;. If the Webdriver/Selenium service is managed by Nightwatch, check if &#34;start_process&#34; is set to &#34;true&#34;.
       at HttpRequest.emit (node:events:369:20)
       at ClientRequest.emit (node:events:381:22)
       at Socket.socketErrorListener (node:_http_client:472:9)
       at Socket.emit (node:events:369:20)
       at emitErrorNT (node:internal/streams/destroy:188:8)
       at emitErrorCloseNT (node:internal/streams/destroy:153:3)
       at processTicksAndRejections (node:internal/process/task_queues:81:21)
    </system-err>
  

    
    <error message="An error occurred while retrieving a new session: &#34;Connection refused to 127.0.0.1:9515&#34;. If the Webdriver/Selenium service is managed by Nightwatch, check if &#34;start_process&#34; is set to &#34;true&#34;."><![CDATA[
      Error: An error occurred while retrieving a new session: &#34;Connection refused to 127.0.0.1:9515&#34;. If the Webdriver/Selenium service is managed by Nightwatch, check if &#34;start_process&#34; is set to &#34;true&#34;.
    at JsonWireProtocol.handleSessionCreateError (D:\mew\my-ether-wallet\node_modules\nightwatch\lib\transport\transport.js:110:15)
    at HttpRequest.&lt;anonymous&gt; (D:\mew\my-ether-wallet\node_modules\nightwatch\lib\transport\transport.js:166:32)
    at HttpRequest.emit (node:events:369:20)
    at ClientRequest.&lt;anonymous&gt; (D:\mew\my-ether-wallet\node_modules\nightwatch\lib\http\request.js:143:19)
    at ClientRequest.emit (node:events:381:22)
    at Socket.socketErrorListener (node:_http_client:472:9)
    at Socket.emit (node:events:369:20)
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
      ]]></error>  

  
    
    <testcase
      name="Access wallet tests" classname="access-wallet">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
